name: .NET Core

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
#     - uses: actions/checkout@v2
      - name: Display the path
        run: echo ${env:PATH}
        shell: pwsh
