name: Build using Unity-Builder

# on:
#  workflow_dispatch:
on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.11f1
        targetPlatform:
#           - StandaloneOSX # Build a macOS standalone (Intel 64-bit).  NOT WORKING DUE TO IL2CPP NOT BEING INCLUEDED IN DOCKER IMAGES
#           - StandaloneWindows64 # Build a Windows 64-bit standalone.  NOT WORKING DUE TO IL2CPP NOT BEING INCLUEDED IN DOCKER IMAGES
#           - StandaloneLinux64 # Build a Linux 64-bit standalone. NOT WORKING DUE TO IL2CPP NOT BEING INCLUEDED IN DOCKER IMAGES
#           - iOS # Build an iOS player. NOT USED
#           - Android # Build an Android player.  NOT WORKING DUE TO https://github.com/webbertakken/unity-builder/issues/167
#           - WSAPlayer # UWP NOT SUPPORTED
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: webbertakken/unity-builder@v1.4
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
